version: '3.2'
services:
  reactapptest:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - '.:/app'
      - '/app/node_modules'

  cypress:
    image: "cypress/included:4.4.0"
    depends_on:
      - reactapptest
    environment:
      - CYPRESS_baseUrl=http://reactapptest:8081/
    working_dir: /e2e
    volumes:
      - ./:/e2e